spring:
  application:
    name: mylibclient
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false

application:
  feign:
    url: http://localhost:8080
server:
  port: 8090